export const actionTypes = {
    SIGNUP_SUCCESS :"SIGNUP_SUCCESS",
    SIGNUP_FAILURE :"SIGNUP_FAILURE",
    SIGNUP_REQUESTED :"SIGNUP_REQUESTED",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGIN_FAILURE : "LOGIN_FAILURE",
    LOGIN_REQUESTED : "LOGIN_REQUESTED",
};
