export const actionTypes = {
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
  SIGNUP_REQUESTED: "SIGNUP_REQUESTED",

  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_REQUESTED: "LOGIN_REQUESTED",

  CREATE_FOLDER_REQUEST: "CREATE_FOLDER_REQUEST",
  CREATE_FOLDER_SUCCESS: "CREATE_FOLDER_SUCCESS",
  CREATE_FOLDER_FAILURE: "CREATE_FOLDER_FAILURE",

  GET_ALL_FOLDERS_REQUEST: "GET_ALL_FOLDERS_REQUEST",
  GET_ALL_FOLDERS_SUCCESS: "GET_ALL_FOLDERS_SUCCESS",
  GET_ALL_FOLDERS_FAILURE: "GET_ALL_FOLDERS_FAILURE",

  RENAME_FOLDER_REQUEST: "RENAME_FOLDER_REQUEST",
  RENAME_FOLDER_SUCCESS: "RENAME_FOLDER_SUCCESS",
  RENAME_FOLDER_FAILURE: "RENAME_FOLDER_FAILURE",

  CREATE_BOOKMARK_REQUEST:"CREATE_BOOKMARK_REQUEST",
  CREATE_BOOKMARK_SUCCESS:"CREATE_BOOKMARK_SUCCESS",
  CREATE_BOOKMARK_FAILURE:"CREATE_BOOKMARK_FAILURE",
};
