export const actionTypes = {
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
  SIGNUP_REQUESTED: "SIGNUP_REQUESTED",

  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_REQUESTED: "LOGIN_REQUESTED",

  GET_USER_REQUEST:"GET_USER_REQUEST",
  GET_USER_SUCCESS:"GET_USER_SUCCESS",
  GET_USER_FAILURE:"GET_USER_FAILURE",

  CREATE_FOLDER_REQUEST: "CREATE_FOLDER_REQUEST",
  CREATE_FOLDER_SUCCESS: "CREATE_FOLDER_SUCCESS",
  CREATE_FOLDER_FAILURE: "CREATE_FOLDER_FAILURE",

  DELETE_FOLDER_REQUEST:"DELETE_FOLDER_REQUEST",
  DELETE_FOLDER_SUCCESS:"DELETE_FOLDER_SUCCESS",
  DELETE_FOLDER_FAILURE:"DELETE_FOLDER_FAILURE",

  GET_ALL_FOLDERS_REQUEST: "GET_ALL_FOLDERS_REQUEST",
  GET_ALL_FOLDERS_SUCCESS: "GET_ALL_FOLDERS_SUCCESS",
  GET_ALL_FOLDERS_FAILURE: "GET_ALL_FOLDERS_FAILURE",

  RENAME_FOLDER_REQUEST: "RENAME_FOLDER_REQUEST",
  RENAME_FOLDER_SUCCESS: "RENAME_FOLDER_SUCCESS",
  RENAME_FOLDER_FAILURE: "RENAME_FOLDER_FAILURE",

  CREATE_BOOKMARK_REQUEST: "CREATE_BOOKMARK_REQUEST",
  CREATE_BOOKMARK_SUCCESS: "CREATE_BOOKMARK_SUCCESS",
  CREATE_BOOKMARK_FAILURE: "CREATE_BOOKMARK_FAILURE",

  DELETE_BOOKMARK_REQUEST: "DELETE_BOOKMARK_REUQEST",
  DELETE_BOOKMARK_SUCCESS: "DELETE_BOOKMARK_SUCCESS",
  DELETE_BOOKMARK_FAILURE: "CREATE_BOOKMARK_FAILURE",

  GET_BOOKMARKS_REQUEST: "GET_BOOKMARKS_REQUEST",
  GET_BOOKMARKS_SUCCESS: "GET_BOOKMARKS_SUCCESS",
  GET_BOOKMARKS_FAILURE: "GET_BOOKMARKS_FAILURE",

  MOVE_BOOKMARK_REQUEST: "MOVE_BOOKMARK_REQUEST",
  MOVE_BOOKMARK_SUCCESS: "MOVE_BOOKMARK_SUCCESS",
  MOVE_BOOKMARK_FAILURE: "MOVE_BOOKMARK_FAILURE",
};
